use std::process::{Command, Stdio};
use std::fs::OpenOptions;
use std::io::Write;
use std::path::Path;

use crate::core::root_check::ensure_admin;
use crate::cli::color_text::{BOLD, GREEN, RED, RESET, YELLOW}; 

const LXC_PATH: &str = "/var/lib/lxc";

pub fn create_new_container(name: &str) {
    if !ensure_admin() { return; }
    
    // 1. Siapkan environment host dulu
    ensure_host_network_ready();

    println!("{}--- Creating Container: {} ---{}", BOLD, name, RESET);
    let process = Command::new("sudo") // Tambahkan sudo lagi di sini jika melisa tidak dijalankan sebagai root
        .args(&[
            "lxc-create", 
            "-P", LXC_PATH, 
            "-t", "download", 
            "-n", name, 
            "--", 
            "-d", "debian", 
            "-r", "bookworm", 
            "-a", "amd64"
        ])
        .output();

    match process {
        Ok(output) => {
            if output.status.success() {
                println!("{}[SUCCESS]{} Container created.", GREEN, RESET);
                
                // 2. Suntikkan konfigurasi network
                inject_network_config(name);
                
                // 3. Setup DNS agar apt update jalan
                setup_container_dns(name);
                
                println!("{}[INFO]{} Network & DNS has been injected successfully.", GREEN, RESET);
            }  else {
                let error_msg = String::from_utf8_lossy(&output.stderr);
                
                if error_msg.contains("already exists") {
                    println!("{}[WARNING]{} Container '{}' sudah ada. Melewati proses pembuatan.", YELLOW, RESET, name);
                    // LOGIC ERROR: Jangan injeksi lagi jika sudah ada untuk menghindari duplikasi config
                } else if error_msg.contains("GPG") {
                    eprintln!("{}[ERROR]{} Masalah tanda tangan GPG. Coba jalankan 'gpg --recv-keys' di host.", RED, RESET);
                } else if error_msg.contains("download") {
                    eprintln!("{}[ERROR]{} Gagal mendownload template. Pastikan koneksi internet host aktif.", RED, RESET);
                } else {
                    eprintln!("{}[ERROR]{} Gagal membuat container: {}", RED, RESET, name);
                    eprintln!("Detail Error: {}", error_msg);
                }
            }
        },
        Err(e) => eprintln!("{}[FATAL]{} Could not run lxc-create: {}", RED, RESET, e),
    }
}

//fungsi memastikan internet container bekerja 
fn inject_network_config(name: &str) {
    let config_path = format!("{}/{}/config", LXC_PATH, name);
    
    if Path::new(&config_path).exists() {
        // Baca dulu isinya
        let content = std::fs::read_to_string(&config_path).unwrap_or_default();
        
        // Jika sudah ada lxc.net.0.link, jangan disuntik lagi!
        if content.contains("lxc.net.0.link") {
            println!("{}[SKIP]{} Network configuration already exists.", YELLOW, RESET);
            return;
        }

        let mut file = OpenOptions::new()
            .append(true)
            .open(&config_path)
            .expect("Gagal membuka config container");

        let net_config = format!(
            "\n# Auto-generated by MELISA\n\
            lxc.net.0.type = veth\n\
            lxc.net.0.link = lxcbr0\n\
            lxc.net.0.flags = up\n\
            lxc.net.0.hwaddr = ee:ec:fa:5e:{:02x}:{:02x}\n", 
            rand::random::<u8>(), rand::random::<u8>()
        );

        file.write_all(net_config.as_bytes()).ok();
    }
}
fn setup_container_dns(name: &str) {
    // Path menuju resolv.conf di dalam rootfs container
    let dns_path = format!("{}/{}/rootfs/etc/resolv.conf", LXC_PATH, name);
    
    let dns_content = "nameserver 8.8.8.8\nnameserver 8.8.4.4\n";
    
    match std::fs::write(&dns_path, dns_content) {
        Ok(_) => println!("{}[INFO]{} DNS configured (Google DNS).", GREEN, RESET),
        Err(e) => eprintln!("{}[ERROR]{} Gagal set DNS: {}", RED, RESET, e),
    }
}

fn ensure_host_network_ready() {
    // Pastikan lxc-net aktif
    Command::new("systemctl")
        .args(&["start", "lxc-net"])
        .output()
        .ok();

    // Pastikan firewalld mengizinkan lxcbr0 (agar internet tidak terblokir)
    Command::new("firewall-cmd")
        .args(&["--zone=trusted", "--add-interface=lxcbr0", "--permanent"])
        .output()
        .ok();
    
    Command::new("firewall-cmd")
        .args(&[ "--reload"])
        .output()
        .ok();
}

pub fn delete_container(name: &str) {
    if !ensure_admin() { return; } // Gerbang Keamanan
    println!("{}--- Deleting Container: {} ---{}", BOLD, name, RESET);

    let process = Command::new("sudo")
        .args(&["lxc-destroy", "-P", LXC_PATH, "-f", "-n", name])
        .output();

    match process {
        Ok(output) => {
            if output.status.success() {
                println!("{}[SUCCESS]{} Container '{}' deleted.", GREEN, RESET, name);
            } else {
                let error_msg = String::from_utf8_lossy(&output.stderr);
                eprintln!("{}[ERROR]{} Failed to delete container: {}", RED, RESET, error_msg);
            }
        },
        Err(e) => eprintln!("{}[FATAL]{} Could not run lxc-destroy: {}", RED, RESET, e),
    }
}

pub fn start_container(name: &str) {
    println!("{}[INFO]{} Starting container '{}'...", GREEN, RESET, name);
    
    let status = Command::new("sudo")
        .args(&["lxc-start", "-P", LXC_PATH, "-n", name, "-d"]) 
        .status();

    match status {
        Ok(s) if s.success() => println!("{}[SUCCESS]{} Container is now running.", GREEN, RESET),
        _ => eprintln!("{}[ERROR]{} Failed to start container. Check if it exists.", RED, RESET),
    }
}

pub fn attach_to_container(name: &str) {
    println!("{}[MODE]{} Entering Saferoom: {}. Type 'exit' to return.", BOLD, name, RESET);

    let _ = Command::new("sudo")
        .args(&["lxc-attach", "-P", LXC_PATH, "-n", name, "--", "bash"])
        .stdout(Stdio::inherit())
        .stderr(Stdio::inherit())
        .stdin(Stdio::inherit())
        .status();
}

pub fn stop_container(name: &str) {
    if !ensure_admin() { return; } // Gerbang Keamanan
    println!("{}[SHUTDOWN]{} Stopping container '{}'...", YELLOW, RESET, name);

    let process = Command::new("sudo")
        .args(&["lxc-stop", "-P", LXC_PATH, "-n", name])
        .output();

    match process {
        Ok(output) => {
            if output.status.success() {
                println!("{}[SUCCESS]{} Container '{}' stopped.", GREEN, RESET, name);
            } else {
                eprintln!("{}[ERROR]{} Failed to stop container.", RED, RESET);
            }
        },
        Err(e) => eprintln!("{}[FATAL]{} Error: {}", RED, RESET, e),
    }
}

pub fn send_command(name: &str, command_args: &[&str]) {
    if command_args.is_empty() {
        eprintln!("{}[ERROR]{} No command provided.", RED, RESET);
        return;
    }

    // 1. CEK STATUS DULU (Pre-flight Check)
    let check_status = Command::new("sudo")
        .args(&["/usr/bin/lxc-info", "-P", LXC_PATH, "-n", name, "-s"])
        .output();

    if let Ok(out) = check_status {
        let output_str = String::from_utf8_lossy(&out.stdout);
        if !output_str.contains("RUNNING") {
            println!("{}[ERROR]{} Container '{}' is NOT running.", RED, RESET, name);
            println!("{}Tip:{} Run 'melisa --run {}' first.", YELLOW, RESET, name);
            return; // Berhenti di sini, jangan lanjut eksekusi
        }
    } else {
        eprintln!("{}[ERROR]{} Gagal mengecek status kontainer.", RED, RESET);
        return;
    }

    // 2. JIKA RUNNING, BARU EKSEKUSI
    println!("{}[SEND]{} Executing on '{}'...", BOLD, name, RESET);

    let status = Command::new("sudo")
        .arg("lxc-attach")
        .arg("-P")
        .arg(LXC_PATH)
        .arg("-n")
        .arg(name)
        .arg("--")
        .args(command_args)
        .stdout(Stdio::inherit())
        .stderr(Stdio::inherit())
        .status();

    // 3. CEK APAKAH PERINTAHNYA BERHASIL
    match status {
        Ok(s) if s.success() => println!("\n{}[DONE]{} Command executed successfully.", GREEN, RESET),
        _ => eprintln!("\n{}[ERROR]{} Command inside container returned an error.", RED, RESET),
    }
}

pub fn list_containers(only_active: bool) {
    println!("{}[INFO]{} Listing containers...", GREEN, RESET);
    
    let mut cmd = Command::new("sudo");
    cmd.args(&["lxc-ls", "-P", LXC_PATH, "--fancy"]);

    if only_active {
        cmd.arg("--active");
    }

    let output = cmd.output();

    match output {
        Ok(out) => {
            if out.status.success() {
                println!("{}", String::from_utf8_lossy(&out.stdout));
            } else {
                eprintln!("{}[ERROR]{} Gagal mengambil daftar.", RED, RESET);
            }
        }
        Err(e) => eprintln!("{}[FATAL]{} Error: {}", RED, RESET, e),
    }
}